name: test-build

# on: [push, pull_request]
on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - doc
      - alpha
      - stable
      - main

jobs:
  test-build:
    name: test-build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install global dependencies
        run: npm install -g cross-env zx tsx

      - name: Install python-setuptools
        if: matrix.os == 'macos-latest'
        run: brew install python-setuptools

      # scripts目录的依赖缓存
      - name: Cache scripts dependencies
        uses: actions/cache@v4
        id: cache-scripts
        with:
          path: scripts/node_modules
          key: ${{ matrix.os }}-node-scripts-${{ hashFiles('scripts/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-scripts-

      # 安装scripts目录依赖（如果缓存未命中）
      - name: Install scripts dependencies
        if: steps.cache-scripts.outputs.cache-hit != 'true'
        run: npm install
        working-directory: ./scripts

      # packages/core 目录的依赖缓存
      - name: Cache core dependencies
        uses: actions/cache@v4
        id: cache-core
        with:
          path: packages/core/node_modules
          key: ${{ matrix.os }}-node-core-${{ hashFiles('packages/core/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-core-

      # 安装 core 目录依赖（如果缓存未命中）
      - name: Install core dependencies
        if: steps.cache-core.outputs.cache-hit != 'true'
        run: npm install
        working-directory: ./packages/core

      # packages/web 目录的依赖缓存
      - name: Cache web dependencies
        uses: actions/cache@v4
        id: cache-web
        with:
          path: packages/web/node_modules
          key: ${{ matrix.os }}-node-web-${{ hashFiles('packages/web/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-web-

      # 安装 web 目录依赖（如果缓存未命中）
      - name: Install web dependencies
        if: steps.cache-web.outputs.cache-hit != 'true'
        run: npm install
        working-directory: ./packages/web

      # packages/electron 目录的依赖缓存
      - name: Cache electron dependencies
        uses: actions/cache@v4
        id: cache-electron
        with:
          path: packages/electron/node_modules
          key: ${{ matrix.os }}-node-electron-${{ hashFiles('packages/electron/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-electron-

      # 安装 electron 目录依赖（如果缓存未命中）
      - name: Install electron dependencies
        if: steps.cache-electron.outputs.cache-hit != 'true'
        run: npm install
        working-directory: ./packages/electron

      # 检查 core 目录ts 类型
      - name: check core types
        run: npx tsc --noEmit
        working-directory: ./packages/core

      # 检查 web 目录ts 类型
      - name: check web types
        run: npx tsc --noEmit
        working-directory: ./packages/web

      # - name: Build Electron App (macOS only)
      #   if: matrix.os == 'macos-latest'
      #   run: npm run prod
      #   env:
      #     APPLE_ID: ${{ secrets.APPLE_ID }}
      #     APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      #     CSC_LINK: ${{ secrets.CSC_LINK }}
      #     CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      #     APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      #     USE_HARD_LINKS: false
      #     MYRUNENV: github

          
      # - name: Build Electron App (Windows+Linux)
      #   if: matrix.os != 'macos-latest'
      #   run: npm run prod
      #   env:
      #     MYRUNENV: github

      # - name: upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.os }}
      #     path: packages/electron/dist

      # - name: Publish Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       dist/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
