name: test-build

# on: [push, pull_request]
on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - doc
      - alpha

jobs:
  test-build:
    name: build and release electron app
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "20"
          cache: "npm"
      # 专门缓存 Electron 二进制文件
      - name: Cache Electron
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('electron/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-


      - name: Install -g
        run: npm install -g cross-env zx

      - name: Install Dependencies
        run: npm install

      - name: Install Web Dependencies
        run: cd web && npm install

      - name: Install python-setuptools
        if: matrix.os == 'macos-latest'
        run: brew install python-setuptools

      - name: Install Electron Dependencies
        run: cd electron && npm install

      - name: Build Electron App (macOS only)
        if: matrix.os == 'macos-latest'
        run: npm run prod
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USE_HARD_LINKS: false
          MYRUNENV: github

      - name: Build Electron App (widnows+linux)
        if: matrix.os != 'macos-latest'
        run: npm run prod
        env:
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MYRUNENV: github

      - name: Test executable
        if: runner.os == 'Windows'
        run: |
          dir dist
          # 尝试启动应用检查错误信息
          Start-Process -FilePath ".\electron\dist\win-unpacked\HyperChat.exe" -NoNewWindow
          # 等待几秒然后检查是否运行
          Start-Sleep -s 5
          Get-Process -Name "HyperChat" -ErrorAction SilentlyContinue

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: electron/dist

      - name: Test executable
        if: runner.os == 'Windows'
        run: |
          dir dist
          # 尝试启动应用检查错误信息
          Start-Process -FilePath ".\dist\win-unpacked\HyperChat.exe" -NoNewWindow
          # 等待几秒然后检查是否运行
          Start-Sleep -s 5
          Get-Process -Name "HyperChat" -ErrorAction SilentlyContinue
      # - name: Publish Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       dist/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
